name: add-vs-solution
author: gendloop
description: 'Add a vs solution for Repo'

runs:
  using: 'composite'
  steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: get-repo-name
      id: get-repo-name
      shell: bash
      run: |
        repo_name=${GITHUB_REPOSITORY#*/}
        echo "reponame=$repo_name" >> "$GITHUB_OUTPUT"

    - name: to-upper
      id: to-upper
      shell: pwsh
      run: |
        $str = "${{ steps.get-repo-name.outputs.reponame }}"
        $upper_str = $str.ToUpper()
        echo "upper_reponame=$upper_str" >> $env:GITHUB_OUTPUT

    - name: add-vs-solution
      working-directory: ${{ github.action_path }}/docs
      shell: bash
      run: |
        repo_name=${{ steps.get-repo-name.outputs.reponame }}
        upper_repo_name=${{ steps.to-upper.outputs.upper_reponame }}
        perl replace.pl NewProject.sln ${repo_name}.sln NewProject ${repo_name}
        perl replace.pl NewProject/NewProject.vcxproj NewProject/${repo_name}.vcxproj NewProject ${repo_name}
        perl replace.pl NewProject/${repo_name}.vcxproj NewProject/${repo_name}.vcxproj XI_EXPORT_TARGET ${upper_repo_name}
        mkdir -p ${{ github.workspace }}/${repo_name}
        cp ${repo_name}.sln ${{ github.workspace }}
        cp NewProject/${repo_name}.vcxproj ${{ github.workspace }}/${repo_name}/${repo_name}.vcxproj
        cp NewProject/NewProject.vcxproj.filters ${{ github.workspace }}/${repo_name}/${repo_name}.vcxproj.filters

    - name: git-push
      uses: gendloop/git-push@v1.0.0
      with:
        token: ${{ github.token }}
        commit: "feat: add vs solution \\`${{ steps.get-repo-name.outputs.reponame }}.sln\\` "
