name: add-vs-solution
author: gendloop
description: 'Add a vs solution for Repo'

runs:
  using: 'composite'
  steps:
    - name: checkout
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0

    - name: add-vs-solution
      working-directory: ${{ github.action_path }}/docs
      shell: pwsh
      run: |
        perl replace.pl NewProject.sln test.sln NewProject test
        perl NewProject/NewProject.vcxproj NewProject/test.vcxproj NewProject test

    - name: copy
      working-directory: ${{ github.action_path }}/docs
      shell: bash
      run: |
        repo_name=${GITHUB_REPOSITORY#*/}
        mkdir ${{ github.workspace }}/${repo_name}
        cp ${repo_name}.sln ${{ github.workspace }}
        cp NewProject/${repo_name}.vcxproj ${{ github.workspace }}/${repo_name}/${repo_name}.vcxproj
        cp NewProject/NewProject.vcxproj.filters ${{ github.workspace }}/${repo_name}/${repo_name}.vcxproj.filters

    - name: push-origin
      working-directory: ${{ github.workspace }}
      shell: bash
      env:
          GITHUB_TOKEN: ${{ github.token }}
      run: |
        repo_name=${GITHUB_REPOSITORY#*/}
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -m "feat: add vs solution `'${repo_name}.sln'` "
        git push
