name: Add_VS_Solution

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  add_submodule:
    runs-on: ubuntu-latest
    steps:
      - name: add-vs-solution
        uses: gendloop/add-vs-solution@main